// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpp2ZMJQHk-6D5P5AMsnoEFpJpW6oFbP0',
    appId: '1:497244459448:web:f38bd73b98a8bcca36ff4d',
    messagingSenderId: '497244459448',
    projectId: 'csgostatsfirebase',
    authDomain: 'csgostatsfirebase.firebaseapp.com',
    storageBucket: 'csgostatsfirebase.appspot.com',
    measurementId: 'G-S0FXH69MDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8acH0v_hqNHP7cC9znb6Ia4lNbixS1hA',
    appId: '1:497244459448:android:4f3d08b0f95b7bee36ff4d',
    messagingSenderId: '497244459448',
    projectId: 'csgostatsfirebase',
    storageBucket: 'csgostatsfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPNg-lk4E-FD9A1ZyK3dK2wZjdlJmhiA',
    appId: '1:497244459448:ios:1ebdff505f0764f936ff4d',
    messagingSenderId: '497244459448',
    projectId: 'csgostatsfirebase',
    storageBucket: 'csgostatsfirebase.appspot.com',
    iosClientId: '497244459448-isgilat7ivif3io687683b9cd7urraml.apps.googleusercontent.com',
    iosBundleId: 'com.example.csgostats',
  );
}
